api_platform:

    allow_plain_identifiers: true
    formats:
        json:
            mime_types: [ 'application/json' ]
        jsonld:
            mime_types: [ 'application/ld+json' ]
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            UUID:
                name: X-USER-UUID
                type: header
